version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/deploy

hooks:
  BeforeInstall:
    - location: scripts/stop_old.sh
      timeout: 300
      runas: ec2-user

  AfterInstall:
    - location: scripts/pull_and_prepare.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start_new.sh
      timeout: 300
      runas: ec2-user
