name: CI, Build Backend Image

on:
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.11.1]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build x86 image (no push)
        run: |
          OWNER="${{ github.repository_owner }}"
          REPO="${{ github.event.repository.name }}"

          OWNER=$(echo "$OWNER" | tr '[:upper:]' '[:lower:]')
          REPO=$(echo  "$REPO"  | tr '[:upper:]' '[:lower:]')

          IMAGE="ghcr.io/${OWNER}/${REPO}"
          TAG=${{ github.sha }}

          docker buildx build \
            --platform linux/amd64 \
            -f apps/backend/Dockerfile \
            --tag $IMAGE:pr-${{ github.event.pull_request.number }} \
            --tag $IMAGE:${{ github.sha }} \
            --load \
            .
